[package]
name = "lazyfood_lib"
version = "0.1.0"
authors = ["Artur Sinila <freesoftware@logarithmus.dev>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.3", features = ["cookies", "gzip", "brotli"] }
select = "0.5.0"
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread"] }
