[package]
name = "lazyfood_lib"
version = "0.1.0"
authors = ["Artur Sinila <freesoftware@logarithmus.dev>"]
edition = "2018"

[dependencies]
html5ever = "0.25.1"
reqwest = { version = "0.11.3", features = ["cookies", "gzip", "brotli"] }
